[package]
name = "ensure_no_std"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2021"

[dependencies]
msp430i20xx = { path = ".." }
msp430-rt = { version = "0.4.0", features = ["device"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
